name: pokemon_pdf_builder
description: Builds PDFs for Pokemon TCG decks for CastFORM.
version: 2.0.2
publish_to: none
# repository: https://github.com/BAA-Studios/CastFORM

environment:
  sdk: '>=3.0.0 <4.0.0'

# dependencies:
#   path: ^1.8.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.9

dependencies:
  pdf: ^3.10.6  # https://pub.dev/packages/pdf
  deck_string_parser:
    path: ../deck_string_parser/
